{
 "title": "DMARC Reports-2024/11/13",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasourceag", "label": "Datasource: Aggregate", "query": "elasticsearch" },
   { "name": "datasourcefo", "label": "Datasource: Forensic", "query": "elasticsearch" },
   {
    "name": "fromdomain",
    "label": "From Domain",
    "query": "{\"find\":\"terms\",\"field\":\"header_from.keyword\"}"
   },
   { "name": "interval", "label": "Interval", "query": "1d" },
   { "name": "Filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "SPF Alignment",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SPF Aligned Pass",
     "bucketAggs": [
      {
       "$$hashKey": "object:244",
       "field": "date_begin",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:241",
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain AND spf_aligned:true",
     "timeField": "date_begin"
    },
    {
     "alias": "SPF Aligned Fail & ARC Pass",
     "bucketAggs": [
      { "field": "date_begin", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain AND spf_aligned:false AND policy_overrides.comment.keyword:arc=pass",
     "timeField": "date_begin"
    },
    {
     "alias": "SPF Aligned Fail & NOT ARC Pass",
     "bucketAggs": [
      { "field": "date_begin", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain AND spf_aligned:false AND NOT policy_overrides.comment.keyword:arc=pass",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "DKIM Alignment",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "DKIM Aligned Pass",
     "bucketAggs": [
      { "field": "date_begin", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain AND dkim_aligned:true",
     "timeField": "date_begin"
    },
    {
     "alias": "DKIM Aligned Fail & ARC Pass",
     "bucketAggs": [
      { "field": "date_begin", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain AND dkim_aligned:false AND policy_overrides.comment.keyword:arc=pass",
     "timeField": "date_begin"
    },
    {
     "alias": "DKIM Aligned Fail & NOT ARC Pass",
     "bucketAggs": [
      { "field": "date_begin", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain AND dkim_aligned:false AND NOT policy_overrides.comment.keyword:arc=pass",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "DMARC Passage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "DMARC Pass",
     "bucketAggs": [
      {
       "field": "date_begin",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:383",
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain AND passed_dmarc:true",
     "timeField": "date_begin"
    },
    {
     "alias": "DMARC Fail & ARC Pass",
     "bucketAggs": [
      { "field": "date_begin", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain AND passed_dmarc:false AND policy_overrides.comment.keyword:arc=pass",
     "timeField": "date_begin"
    },
    {
     "alias": "DMARC Fail & NOT ARC Pass",
     "bucketAggs": [
      { "field": "date_begin", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain AND passed_dmarc:false AND NOT policy_overrides.comment.keyword:arc=pass",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "SPF Results Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "spf_results.result.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "date_begin", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "DKIM Results Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dkim_results.result.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "date_begin", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "SPF Alignment Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "spf_aligned",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "date_begin", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "DKIM Alignment Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dkim_aligned",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "date_begin", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "DMARC Passage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "passed_dmarc",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "date_begin", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "Message Disposition Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "disposition.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "date_begin", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "message_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total Message Count",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:430",
       "fake": true,
       "field": "date_begin",
       "id": "6",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:428",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "Top 2000 Message Sources by Reverse DNS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:920",
       "fake": true,
       "field": "source_base_domain.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "none",
        "order": "desc",
        "orderBy": "4",
        "size": "2000"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:918",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "Reporting Organisations",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:291",
       "fake": true,
       "field": "org_name.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:98",
       "fake": true,
       "field": "org_extra_contact_info.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:96",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "Message Volume by Header From",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:388",
       "fake": true,
       "field": "header_from.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "none",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:386",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "Map of Message Source Countries",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "source_country.keyword",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "4", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:708",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "Message Source Countries",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:524",
       "fake": true,
       "field": "source_country.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "none",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:522",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:457",
       "fake": true,
       "field": "source_base_domain.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:458",
       "fake": true,
       "field": "source_reverse_dns.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:459",
       "fake": true,
       "field": "source_ip_address.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:460",
       "fake": true,
       "field": "source_country.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "4", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:384",
       "fake": true,
       "field": "disposition.keyword",
       "id": "12",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:391",
       "fake": true,
       "field": "spf_aligned",
       "id": "13",
       "settings": {
        "min_doc_count": "1",
        "missing": "false",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:398",
       "fake": true,
       "field": "dkim_aligned",
       "id": "14",
       "settings": {
        "min_doc_count": "1",
        "missing": "false",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:405",
       "fake": true,
       "field": "org_name.keyword",
       "id": "15",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:412",
       "fake": true,
       "field": "spf_results.result.keyword",
       "id": "16",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:622",
       "fake": true,
       "field": "header_from.keyword",
       "id": "17",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:461",
       "fake": true,
       "field": "dkim_results.result.keyword",
       "id": "10",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "policy_overrides.comment.keyword",
       "id": "18",
       "settings": {
        "min_doc_count": "1",
        "missing": "N/A",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "passed_dmarc",
       "id": "19",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:455",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "Published Policies (as reported)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:457",
       "fake": true,
       "field": "published_policy.adkim.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:458",
       "fake": true,
       "field": "published_policy.aspf.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:459",
       "fake": true,
       "field": "published_policy.domain.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:460",
       "fake": true,
       "field": "published_policy.fo.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "4", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:384",
       "fake": true,
       "field": "published_policy.p.keyword",
       "id": "12",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:391",
       "fake": true,
       "field": "published_policy.pct",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:398",
       "fake": true,
       "field": "published_policy.sp.keyword",
       "id": "14",
       "settings": {
        "min_doc_count": "1",
        "missing": "false",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:455",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "Top 1000 Message Source IP Addresses",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:921",
       "fake": true,
       "field": "source_ip_address.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "1000"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:922",
       "fake": true,
       "field": "source_reverse_dns.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "1000"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:923",
       "fake": true,
       "field": "source_base_domain.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "1000"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:924",
       "fake": true,
       "field": "source_country.keyword",
       "id": "9",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "1000"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:919",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_begin"
    }
   ]
  },
  {
   "title": "SPF Alignment Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:457",
       "fake": true,
       "field": "header_from.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:458",
       "fake": true,
       "field": "envelope_from.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:459",
       "fake": true,
       "field": "spf_results.result.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:460",
       "fake": true,
       "field": "spf_aligned",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "4", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:461",
       "fake": true,
       "field": "source_base_domain.keyword",
       "id": "10",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "policy_overrides.comment.keyword",
       "id": "11",
       "settings": {
        "min_doc_count": "1",
        "missing": "N/A",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "source_ip_address.keyword",
       "id": "12",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "passed_dmarc",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:455",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "DKIM Alignment Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:457",
       "fake": true,
       "field": "header_from.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:458",
       "fake": true,
       "field": "dkim_results.selector.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:459",
       "fake": true,
       "field": "dkim_results.domain.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:460",
       "fake": true,
       "field": "dkim_results.result.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "4", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:798",
       "fake": true,
       "field": "dkim_aligned",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:461",
       "fake": true,
       "field": "source_base_domain.keyword",
       "id": "10",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "4",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "passed_dmarc",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "policy_overrides.comment.keyword",
       "id": "13",
       "settings": {
        "min_doc_count": "1",
        "missing": "N/A",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:455",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "header_from.keyword:$fromdomain",
     "timeField": "date_range"
    }
   ]
  },
  {
   "title": "DMARC Forensic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Forensic Samples",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:340",
       "fake": true,
       "field": "arrival_date",
       "id": "6",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      },
      {
       "$$hashKey": "object:341",
       "fake": true,
       "field": "sample.headers.from.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:342",
       "fake": true,
       "field": "sample.headers.to.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:343",
       "fake": true,
       "field": "sample.headers.reply-to.keyword",
       "id": "10",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:344",
       "fake": true,
       "field": "auth_failure.keyword",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:345",
       "fake": true,
       "field": "sample.subject.keyword",
       "id": "12",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:346",
       "fake": true,
       "field": "delivery_results.keyword",
       "id": "14",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:347",
       "fake": true,
       "field": "authentication_results.keyword",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:348",
       "fake": true,
       "field": "sample.headers.received.keyword",
       "id": "13",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "sample.date",
       "id": "16",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "source_ip_address.keyword",
       "id": "17",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "source_reverse_dns.keyword",
       "id": "18",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "domain.keyword",
       "id": "19",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:338",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "domain.keyword:$fromdomain",
     "timeField": "arrival_date"
    }
   ]
  },
  {
   "title": "Forensic Sample Sources by Country",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source_country.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "arrival_date",
       "id": "10",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "4", "type": "count" }
     ],
     "query": "domain.keyword:$fromdomain",
     "timeField": "arrival_date"
    }
   ]
  },
  {
   "title": "DMARC Forensic Sample Source Countries",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 8, "y": 116 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:840",
       "fake": true,
       "field": "source_country.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "none",
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:838",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "domain.keyword:$fromdomain",
     "timeField": "arrival_date"
    }
   ]
  },
  {
   "title": "Top 1000 Forensic Sample Source IP Addresses",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 116 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:653",
       "fake": true,
       "field": "source_ip_address.keyword",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "1000"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:654",
       "fake": true,
       "field": "source_reverse_dns.keyword",
       "id": "7",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "1000"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:655",
       "fake": true,
       "field": "source_base_domain.keyword",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "1000"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:656",
       "fake": true,
       "field": "source_country.keyword",
       "id": "9",
       "settings": {
        "min_doc_count": 1,
        "missing": "-",
        "order": "desc",
        "orderBy": "_count",
        "size": "1000"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:651",
       "field": "message_count",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "domain.keyword:$fromdomain",
     "timeField": "arrival_date"
    }
   ]
  }
 ]
}